services:
  the-forest-server:
    build: .
    container_name: the-forest-server
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
    volumes:
      - ./data:/server-data
    tty: true
    privileged: true
